name: Deploy Infra

# Automatic deploy to master brnach after a successsful push event.
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Infra
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.7.5  

    - name: Terraform Init
      run: terraform init
 
    - name: Terraform Plan
      if: github.event_name == 'push'
      run: terraform plan 

    - name: Terraform Deploy
      run: terraform apply